##################################
name: gitflow-action
on: 
  # To create pull requests.
  push:
  # To merge pull requests if not possible during the push run. Remove if `auto-merge` is `false`.
  # Para fusionar solicitudes de extracción si no es posible durante la ejecución de inserción. Eliminar si `auto-merge` si es` falso`.
  pull_request_review:
  check_run:
    types: [completed]

jobs:
  build:
    name: Gitflow
    runs-on: ubuntu-16.04
    steps:
    - uses: Logerfo/gitflow-action@0.0.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # The `GITHUB_TOKEN` secret.
        release: release # The `release` branch.
        dev: develop # The `dev` branch.
        master: master # The `master` branch.
        label: gitflow # The pull request label.
        # If auto-merge `true`, will try to automatically merge pull requests. Can also be set to `pull_request_review`, `check_run`, `push`, or a comma-separated combination of these values to only merge when handling the named events.
        # Si auto-merge es "verdadero", intentará fusionar automáticamente las solicitudes de extracción. 
        # También se puede configurar en `pull_request_review`,` check_run`, `push`, o una combinación separada por comas de estos valores para fusionar 
        # solo cuando se manejan los eventos nombrados.
        auto-merge: true 
        require-merge: false #Si falla un intento de fusión, se considera que la acción ha fallado.

##################################
